# Generated by Django 2.1.8 on 2019-07-13 02:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Name',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
            ],
            options={
                'verbose_name_plural': 'Name',
            },
        ),
        migrations.CreateModel(
            name='Salary',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('salary', models.IntegerField()),
            ],
            options={
                'verbose_name_plural': 'Salary',
            },
        ),
        migrations.CreateModel(
            name='Work',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('work', models.CharField(max_length=150)),
                ('salary', models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, to='main.Salary', verbose_name='Salary')),
            ],
            options={
                'verbose_name_plural': 'Work',
            },
        ),
        migrations.AddField(
            model_name='name',
            name='salary',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, to='main.Salary', verbose_name='Salary'),
        ),
        migrations.AddField(
            model_name='name',
            name='work',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, to='main.Work', verbose_name='Work'),
        ),
    ]
